name: CustomTabBukkit
main: fr.atesab.customtagb.CustomTabPlugin
version: 1.3
description: A plugin to change tab
author: ATE47
commands:
  ltab:
    description: use ltab command
    permission: ctp.ltab
    aliases: [localtab]
    usage: /ltab
permissions:
  ctp.ltab:
    description: use ltab command
    default: op
  ctp.ltab.reload:
    description: Reload config
    default: op
  ctp.ltab.opt:
    description: Show available text options
    default: op
  ctp.ltab.show:
    description: Show tab part
    default: op
  ctp.ltab.delline:
    description: Delete a line
    default: op
  ctp.ltab.addline:
    description: Add a line
    default: op
  ctp.ltab.setline:
    description: Set a line
    default: op